language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.6.4

install:
  - pip install -q $DJANGO && pip install sphinx argparse
  - python setup.py -q install
script: python runtests.py
